---
title: "Population change map"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Interactive-map}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, echo=FALSE}
library(testmap)
```


```{r load-packages, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(leaflet)
library(leafem)
library(sf)
```

Use the interactive map to check population changes.
```{r make-map, echo=FALSE, message=FALSE, warning=FALSE}
points_bau4326 <- points_bau |> 
  #filter(BASIN_N == "Orinoco") |>
  arrange(BASIN_N, SUBBASI, BB_ID, REACH_ID) |> 
  filter(row_number() %% 5 == 1) |> st_as_sf() |> st_transform(4326)
points_bau4326_low <- points_bau4326
# colour palette
pal <- colorFactor(
  palette = c("#7274C1", "#A3720E"),
  domain = points_bau4326$flag_50_42y
)
 # basemap with tile control. not working.
basemap <- leaflet::leaflet() %>%
  # add different provider tiles
  addProviderTiles(
    "OpenStreetMap",
    # give the layer a name
    group = "OpenStreetMap"
  ) %>%
  addProviderTiles(
    "Stamen.Terrain",
    group = "Stamen.Terrain"
  ) %>%
  addProviderTiles(
    "Esri.WorldImagery",
    group = "Esri.WorldImagery"
  ) %>%
# add a layers control
  addLayersControl(
    baseGroups = c(
      "OpenStreetMap", "Stamen.Terrain", "Esri.WorldImagery"
    ),
    # position it on the topleft
    position = "topleft"
  )

# interactive map
leaflet::leaflet(data = points_bau4326) |> 
  addTiles() |>
  addCircleMarkers(color = ~pal(flag_50_42y), 
             stroke = FALSE, fillOpacity = 0.4, 
clusterOptions = markerClusterOptions(), 
group = "points_bau4326"
) |>                        
  groupOptions("points_bau4326", zoomLevels = 1:8) |> 
  addCircles(data = points_bau4326_low, 
             color = ~pal(flag_50_42y), 
group = "points_bau4326_low"
) |>                        
  groupOptions("points_bau4326_low", zoomLevels = 9:15) |> 
  addScaleBar() |> 
  leafem::addMouseCoordinates()

  
```

